apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-fleet
data:
  REDIS_HOST: {{ .Values.redisConnection.host | quote }}
  REDIS_PORT: {{ .Values.redisConnection.port | quote }}
  REDIS_ADDRESS: "{{ .Values.redisConnection.host }}:{{ .Values.redisConnection.port }}"
