server:
  port: 8092

spring:
  application:
    name: openframe-external-api
  main:
    web-application-type: servlet
  data:
    mongodb:
      enabled: true
    cassandra:
      enabled: true
    redis:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
      - org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.cassandra.CassandraReactiveDataAutoConfiguration'
  oss-tenant:
    kafka:
      bootstrap-servers: kafka.datasources.svc.cluster.local:9092
      enabled: true

management:
  server:
    port: 8093

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    
openframe:
  integration:
    tactical-rmm:
      url: http://tactical-nginx.integrated-tools.svc.cluster.local:8000
    fleet-mdm:
      url: http://fleetmdm-server.integrated-tools.svc.cluster.local:8070
    meshcentral:
      url: http://meshcentral-server.integrated-tools.svc.cluster.local:80
  oss-tenant:
    kafka:
      topics:
        outbound:
          openframe-events: openframe.events
          devices-topic: devices-topic
