apiVersion: apps/v1
kind: Deployment
metadata:
  name: openframe-external-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openframe-external-api
  template:
    metadata:
      labels:
        app: openframe-external-api
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        prometheus.io/port: "8093"
        prometheus.io/path: "/management/{{ .Values.global.image.tag }}/prometheus"

    spec:
      initContainers:
        - name: wait-for-management-server
          image: "{{ .Values.initImage.registry }}/{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
          command: ["sh", "-c", "until curl -f http://openframe-management.microservices.svc.cluster.local:8096/management/{{ .Values.global.image.tag }}/health; do sleep 1; done"]
          
      containers:
        - name: openframe-external-api
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Values.image.tag .Values.global.image.tag }}"
          ports:
            - containerPort: 8092
              name: http
            - containerPort: 8093
              name: management
          env:
            - name: OPENFRAME_SECURITY_JWT_ALLOWED_ISSUER_BASE
              value: "http://openframe-authorization-server.microservices.svc.cluster.local:9005/sas"
          envFrom:
            - configMapRef:
                name: microservices

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /management/{{ .Values.global.image.tag }}/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /management/{{ .Values.global.image.tag }}/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
